typography_spectrum: 0.47871156712062657
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.03788975230418146
analytics:
  google: null
  facebook: null
  twitter: null
name: bda
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hello
description: world
purpose: []
